### ISSUE TITLE
What should I do if I want to contribute new puzzles to the app? 

### ISSUE THREAD

**Issue by hongwai1920** [atorch/probability_puzzles#6]
As mentioned in the title, if I found some interesting puzzles and would like them to be included in the app, what should I do?

**Comment by atorch** [comment]
Good question!  Have a look at https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.  For an example of a past pull request from someone other than me, see https://github.com/atorch/probability_puzzles/pull/4 (but note that this pull request improved an existing puzzle rather than adding new ones).  For a pull request from me that adds new puzzles (but hasn't yet been merged), see https://github.com/atorch/probability_puzzles/pull/2.

You wrote that you _found_ some interesting puzzles.  Where did you find them?

**Comment by hongwai1920** [comment]
I found the book https://www.springer.com/gp/book/9780387941615 contains some interesting probability problems.

**Comment by atorch** [comment]
I see. I wrote all of the puzzles in this app myself -- some of them are inspired either by classic puzzles (Monty Hall) or by textbook problems, but they are never copied directly (or even close to directly) from another text. If you are interested in contributing puzzles to the app, please do the same, i.e. write them yourself without lifting or copying anything directly from another text. If you're interested in doing that, I'd be very happy to review your pull request! Thank you for opening this issue, I appreciate the question.

**Comment by hongwai1920** [comment]
Noted. Thanks.
